### ISSUE TITLE
Add student enrollment data management

### ISSUE THREAD

**Issue by kwannoel** [AY2021S1-CS2103T-F11-1/tp#2]
As a user, I can CRUD student details into my data, so that I can add/remove my students data when they join/drop the module.

# Student data

- Name
- Matric card number
- NUS Email
- Telegram

# Subtasks

- [x] [Allow users to add students data](#12)
- [x] [Allow users to read students data](#13)
- [x] [Allow users to update students data](#14)
- [x] [Allow users to delete students data](#15)

**Comment by kwannoel** [comment]
Sub PRs closed.
