### ISSUE TITLE
Add attendance management

### ISSUE THREAD

**Issue by kwannoel** [AY2021S1-CS2103T-F11-1/tp#3]
As a user, I can CRUD my students’ attendance so that I can keep track of my students’ attendance.

# Subtasks

- [x] [Create student attendance tracker](#6)
- [x] [View student attendance](#7)
- [x] [Update student attendance](#9)
- [x] [Delete student from attendance](#10)
- [x] [Delete student attendance tracker](#11)
